version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: universal
      POSTGRES_USER: spb0122003
      POSTGRES_PASSWORD: dcaGRzkJpuKsHgMs8hoS
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: